package com.purvar.drools;

import com.purvar.drools.entity.Message;
import java.util.concurrent.atomic.AtomicInteger;

global String temp;
global AtomicInteger count;

//函数示例
function void print(String messgae){
    System.out.println(messgae);
}

//规则1
rule "say-hi"
    when
        $message: Message(Message.MessageType.HI.equals(messageType) && target!=null)
    then
        print("hi," + $message.getMessageType() + ", welcome to drools\n");
        print("hi," + $message.getTarget() + ", welcome to drools\n");
    end

//规则2，模糊匹配
rule "say-hi-like"
    when
        $message: Message(target contains name && target!=null)
    then
        print("hi," + $message.getName() + ", welcome to drools contains\n");
    end

//规则3， 执行model里的方法
rule "say-hi-add"
    when
        $message: Message(add("宁") && target!=null)
    then
        print("hi," + $message.getTarget() + ", welcome to drools contains\n");
    end